Apply try-catch
coderaiser/minify pull request #78
Opened 2021-09-18 17:03 UTC by theyup12

I apply the try-catch and refactor into shorter code in lib/libOptions

2021-09-18 20:37 UTC, coderaiser requested changes
That's amazing, thank you! Please remove `ChangeLog` changes and run `npm run fix:lint`.

2021-09-18 20:37 UTC, coderaiser commented on lib/options.js
> +    const [error, options] = tryCatch(JSON.parse, readFile(filePath));
```suggestion
    const [error, options] = tryCatch(JSON.parse, readFile, filePath)); 
```

2021-09-18 20:37 UTC, coderaiser commented on lib/options.js
> +    return options;
```suggestion
    return [null, options];
```

2021-09-18 20:37 UTC, coderaiser commented on lib/options.js
> +        return {error: new Error(`Options file at ${filePath} could not be parsed with error\n${err.message}`)};
```suggestion
        return [new Error(`Options file at ${filePath} could not be parsed with error\n${err.message}`), null];
```

2021-09-18 20:54 UTC, theyup12 commented
I'm sorry, seems like a lot error, What should I do to fix it?

2021-09-18 23:17 UTC, coderaiser requested changes

2021-09-18 23:17 UTC, coderaiser commented on ChangeLog
> +2021.09.17,v7.1.0
```suggestion
```

2021-09-18 23:17 UTC, coderaiser commented on ChangeLog
> +feature:
```suggestion
```

2021-09-18 23:17 UTC, coderaiser commented on ChangeLog
> +- (package) try-catch v3.0.0
```suggestion
```

2021-09-18 23:19 UTC, coderaiser commented
Run `npm run fix:lint` :).

2021-09-20 09:01 UTC, coderaiser commented
Could you please update `bin/minif.js` and tests?

2021-09-21 20:24 UTC, theyup12 commented
I have issues on using madrun

2021-09-28 13:10 UTC, coderaiser commented
Landed in [v7.2.0](https://github.com/coderaiser/minify/releases/tag/v7.2.0) 🎉

2021-09-28 13:10 UTC, closed without merging